# .github/actions/setup-terraform-terragrunt/action.yml
name: 'Setup Terraform and Terragrunt'
description: 'Installs Terraform and Terragrunt with specified versions'

inputs:
  terraform_version:
    description: 'Terraform version to install'
    required: false
    default: '1.10.0'
  terragrunt_version:
    description: 'Terragrunt version to install'
    required: false
    default: '0.77.1'

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      shell: bash
      run: |
        TERRAFORM_VERSION="${{ inputs.terraform_version }}"
        TERRAFORM_PLATFORM="linux_amd64"
        TERRAFORM_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${TERRAFORM_PLATFORM}.zip"
        
        echo "Installing Terraform v${TERRAFORM_VERSION}..."
        curl -Lo terraform.zip $TERRAFORM_URL
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/terraform
        sudo chmod +x /usr/local/bin/terraform
        
        export TERRAGRUNT_TFPATH="/usr/local/bin/terraform"
        terraform version
    
    - name: Setup Terragrunt
      shell: bash
      run: |
        TERRAGRUNT_VERSION="${{ inputs.terragrunt_version }}"
        
        echo "Installing Terragrunt v${TERRAGRUNT_VERSION}..."
        sudo curl -Lo /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
        sudo chmod +x /usr/local/bin/terragrunt
        
        terragrunt --version